/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itenas.is.oop.uasproject.gymproject.dbviewswing;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.itenas.is.oop.uasproject.gymproject.dbImplgym.MenuCRUD;
import org.itenas.is.oop.uasproject.gymproject.dbconfig.ConnectionManager;
import org.itenas.is.oop.uasproject.gymproject.model.MenuGym;
import org.itenas.is.oop.uasproject.gymproject.model.User;

/**
 *
 * @author LENOVO
 */
public class ViewMenuOwner extends javax.swing.JFrame {
    MenuCRUD conMenu = new MenuCRUD(new ConnectionManager());
    private DefaultTableModel model;
    private User user;
    public ViewMenuOwner(User user) {
        this.user = user;
        initComponents();
        setLocationRelativeTo(null);
        loadKategoriToComboBox();
        model = new DefaultTableModel();
        
        dataMenu.setModel(model);
        
        model.addColumn("ID");
        model.addColumn("NAMA");
        model.addColumn("JENIS PENGUNJUNG");
        model.addColumn("HARGA");
        model.addColumn("MASA AKTIF");
        model.addColumn("DESKRIPSI");
        getData();
    }
    
    public final void getData() {
        DefaultTableModel dtm = (DefaultTableModel) dataMenu.getModel();
        dtm.setRowCount(0);
        List<MenuGym> listMenu = conMenu.findAll();
        Object[] data = new Object[6];

        for (MenuGym dataMenu : listMenu) {
            data[0] = dataMenu.getIdKategori();
            data[1] = dataMenu.getNamaMenu();
            data[2] = dataMenu.getJenisPengunjung();
            data[3] = dataMenu.getHarga();
            data[4] = dataMenu.getDurasi();
            data[5] = dataMenu.getDeskripsi();
            dtm.addRow(data);
        }
    }
    
    private void clearData() {
        txtNama.setText("");
        txtHarga.setText("");
        txtDurasi.setText("");
        txtDeskripsi.setText("");
        getData();
    }
    
        private void loadKategoriToComboBox() {
        try {
            // Hapus semua item dari combo box
            boxJenis.removeAllItems();

            // Tambahkan pilihan ke combo box
            boxJenis.addItem("MEMBER");
            boxJenis.addItem("VISITOR");

            System.out.println("Kategori berhasil dimuat.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error memuat kategori: " + e.getMessage());
        }
}



    private String getSelectedKategori() {
    String selectedKategori = (String) boxJenis.getSelectedItem();

    if (selectedKategori != null && !selectedKategori.isEmpty()) {
        return selectedKategori; 
    }

    return null; 
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        panelNavbar13 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JLabel();
        btnViewTransaksi = new rojerusan.RSMaterialButtonRectangle();
        btnViewPengguna = new rojerusan.RSMaterialButtonRectangle();
        jPanel2 = new javax.swing.JPanel();
        labelharga = new javax.swing.JLabel();
        labeltglmasuk = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtDurasi = new javax.swing.JTextField();
        btnSubmited = new rojerusan.RSMaterialButtonRectangle();
        btnUpdated = new rojerusan.RSMaterialButtonRectangle();
        btnDeleted = new rojerusan.RSMaterialButtonRectangle();
        btnCleared = new rojerusan.RSMaterialButtonRectangle();
        labelnama = new javax.swing.JLabel();
        labeltglmasuk1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataMenu = new javax.swing.JTable();
        labeltglmasuk2 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        boxJenis = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        panelNavbar13.setBackground(new java.awt.Color(204, 204, 204));

        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\PBO\\PROJECT_UAS\\Img\\Fitness-Gym-logo-design-template-on-transparent-background-PNG__1_-removebg-preview (2).png")); // NOI18N

        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\PBO\\PROJECT_UAS\\Img\\logout (1).png")); // NOI18N
        btnlogout.setText("LogOut");
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
        });

        btnViewTransaksi.setBackground(new java.awt.Color(153, 153, 153));
        btnViewTransaksi.setText("DATA MENU");
        btnViewTransaksi.setToolTipText("");
        btnViewTransaksi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnViewTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTransaksiActionPerformed(evt);
            }
        });

        btnViewPengguna.setBackground(new java.awt.Color(153, 153, 153));
        btnViewPengguna.setText("DATA PENGHASILAN");
        btnViewPengguna.setToolTipText("");
        btnViewPengguna.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnViewPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPenggunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNavbar13Layout = new javax.swing.GroupLayout(panelNavbar13);
        panelNavbar13.setLayout(panelNavbar13Layout);
        panelNavbar13Layout.setHorizontalGroup(
            panelNavbar13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavbar13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnlogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNavbar13Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(panelNavbar13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(30, 30, 30))
        );
        panelNavbar13Layout.setVerticalGroup(
            panelNavbar13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavbar13Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel40)
                .addGap(152, 152, 152)
                .addComponent(btnViewTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        labelharga.setText("Deskripsi");

        labeltglmasuk.setText("Durasi");

        txtNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtDurasi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtDurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurasiActionPerformed(evt);
            }
        });

        btnSubmited.setText("CREATE");
        btnSubmited.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        btnSubmited.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitedActionPerformed(evt);
            }
        });

        btnUpdated.setBackground(new java.awt.Color(255, 204, 0));
        btnUpdated.setText("UPDATE");
        btnUpdated.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        btnUpdated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatedActionPerformed(evt);
            }
        });

        btnDeleted.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleted.setText("DELETE");
        btnDeleted.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        btnDeleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletedActionPerformed(evt);
            }
        });

        btnCleared.setBackground(new java.awt.Color(102, 255, 102));
        btnCleared.setText("Clear");
        btnCleared.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        btnCleared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearedActionPerformed(evt);
            }
        });

        labelnama.setText("Nama Menu");

        labeltglmasuk1.setText("Jenis Pengunjung");

        dataMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID MENU", "Nama Menu", "Jenis Pengunjung", "Harga", "Durasi", "Deskripsi"
            }
        ));
        dataMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataMenu);

        labeltglmasuk2.setText("Harga");

        txtHarga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        jScrollPane2.setViewportView(txtDeskripsi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labeltglmasuk)
                                .addGap(18, 18, 18)
                                .addComponent(txtDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelharga)
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(labeltglmasuk1)
                                .addGap(18, 18, 18)
                                .addComponent(boxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labeltglmasuk2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(labelnama)
                                .addGap(18, 18, 18)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnDeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmited, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltglmasuk)
                    .addComponent(txtDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(labeltglmasuk2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(boxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labeltglmasuk1))
                            .addComponent(labelharga))
                        .addGap(26, 26, 26)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmited, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(panelNavbar13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(panelNavbar13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMenuMouseClicked
        // TODO add your handling code here:
        int i = dataMenu.getSelectedRow();

        TableModel model = dataMenu.getModel();
        txtNama.setText(model.getValueAt(i, 1).toString());
        boxJenis.setSelectedItem(model.getValueAt(i, 2).toString()); 
        txtHarga.setText(model.getValueAt(i, 3).toString());
        txtDurasi.setText(model.getValueAt(i, 4).toString());
        txtDeskripsi.setText(model.getValueAt(i, 5).toString());
        
    }//GEN-LAST:event_dataMenuMouseClicked

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(ViewMenuOwner.this,
            "Are you sure you want to logout?", "Logout Confirmation",
            JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            user.setRole(null); // Clear user role
            user.setUsername(null); // Clear username
            JOptionPane.showMessageDialog(ViewMenuOwner.this, "You have been logged out.");
            dispose(); // Close AdminDashboard
            new ViewLogIn().setVisible(true); // Open Login Form
        }
    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnViewTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTransaksiActionPerformed
        // TODO add your handling code here:
        new ViewMenuOwner(user).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewTransaksiActionPerformed

    private void btnViewPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPenggunaActionPerformed
        // TODO add your handling code here:
        new ViewPenghasilanOwner(user).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewPenggunaActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtDurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurasiActionPerformed

    private void btnSubmitedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitedActionPerformed
        // TODO add your handling code here:
                                                   
    try {
        
        String namaMenu = txtNama.getText();    
        String jenisPengunjung = (String) boxJenis.getSelectedItem();
        double harga = Double.parseDouble(txtHarga.getText());
        int durasi = Integer.parseInt(txtDurasi.getText());
        String deskripsi = txtDeskripsi.getText();

        if (namaMenu.isEmpty() || jenisPengunjung.isEmpty() || deskripsi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field wajib diisi!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }

        MenuGym menuGym = new MenuGym();
        menuGym.setNamaMenu(namaMenu);
        menuGym.setJenisPengunjung(jenisPengunjung);
        menuGym.setHarga(harga);
        menuGym.setDurasi(durasi);
        menuGym.setDeskripsi(deskripsi);
        
        conMenu.create(menuGym);

        JOptionPane.showMessageDialog(this, "Menu berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        // Bersihkan form
        clearData();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harap masukkan data dengan format yang benar (angka untuk ID, harga, durasi)!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        }

    }//GEN-LAST:event_btnSubmitedActionPerformed

    private void btnUpdatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatedActionPerformed
        // TODO add your handling code here:
        int i = dataMenu.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(btnUpdated, "Harap pilih salah satu data",
                "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    try {
            String idMenu = dataMenu.getModel().getValueAt(i, 0).toString();
            String namaMenu = txtNama.getText();
            String jenisPengunjung = boxJenis.getSelectedItem().toString();
            double harga = Double.parseDouble(txtHarga.getText());
            int durasi = Integer.parseInt(txtDurasi.getText());
            String deskripsi = txtDeskripsi.getText();

            // Buat objek MenuGym
            MenuGym menuGym = new MenuGym();
            menuGym.setNamaMenu(namaMenu);
            menuGym.setJenisPengunjung(jenisPengunjung);
            menuGym.setHarga(harga);
            menuGym.setDurasi(durasi);
            menuGym.setDeskripsi(deskripsi);

            conMenu.update(idMenu, menuGym);

            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            clearData(); // Membersihkan input setelah operasi selesai
            getData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdatedActionPerformed

    private void btnDeletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletedActionPerformed
        // TODO add your handling code here:
        int i = dataMenu.getSelectedRow();

        if (i == -1) {
            JOptionPane.showMessageDialog(btnDeleted, "Harap pilih salah satu data",
                "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int id = Integer.parseInt(dataMenu.getModel().
            getValueAt(i, 0).toString());

        conMenu.delete(id);
        JOptionPane.showMessageDialog(btnDeleted, "Data berhasil diHapus");
        getData();
        clearData();
    }//GEN-LAST:event_btnDeletedActionPerformed

    private void btnClearedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearedActionPerformed
        // TODO add your handling code here:
        getData();
        clearData();
    }//GEN-LAST:event_btnClearedActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxJenis;
    private rojerusan.RSMaterialButtonRectangle btnCleared;
    private rojerusan.RSMaterialButtonRectangle btnDeleted;
    private rojerusan.RSMaterialButtonRectangle btnSubmited;
    private rojerusan.RSMaterialButtonRectangle btnUpdated;
    private rojerusan.RSMaterialButtonRectangle btnViewPengguna;
    private rojerusan.RSMaterialButtonRectangle btnViewTransaksi;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JTable dataMenu;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelharga;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labeltglmasuk;
    private javax.swing.JLabel labeltglmasuk1;
    private javax.swing.JLabel labeltglmasuk2;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelNavbar13;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtDurasi;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
