/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itenas.is.oop.uasproject.gymproject.dbviewswing;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.itenas.is.oop.uasproject.gymproject.model.DataPengguna;
import org.itenas.is.oop.uasproject.gymproject.dbImplgym.PenggunaCRUD;
import org.itenas.is.oop.uasproject.gymproject.dbconfig.ConnectionManager;
import org.itenas.is.oop.uasproject.gymproject.model.DataPengguna;
import org.itenas.is.oop.uasproject.gymproject.model.User;

/**
 *
 * @author Hafiz Yazid
 */
public class ViewDataAnggota extends javax.swing.JFrame {
    PenggunaCRUD conData = new PenggunaCRUD(new ConnectionManager()); 
    private DefaultTableModel model;
    
    private User user;
    
    public ViewDataAnggota(User user) {
        this.user = user;
        initComponents();
        setLocationRelativeTo(null);
        model = new DefaultTableModel();
        
        dataAnggota.setModel(model);
        
        model.addColumn("ID");
        model.addColumn("NAMA");
        model.addColumn("EMAIL");
        model.addColumn("ALAMAT");
        model.addColumn("NOHP");
        getData();
    }
    
    public final void getData() {
            DefaultTableModel dtm = (DefaultTableModel) dataAnggota.getModel();
           dtm.setRowCount(0); 

     
           List<DataPengguna> listData = conData.findAll(); 
           Object[] data = new Object[5]; 

       for (DataPengguna pengguna : listData) {
           data[0] = pengguna.getIdPengguna();
           data[1] = pengguna.getNamaPengguna();
           data[2] = pengguna.getEmailPengguna();
           data[3] = pengguna.getAlamatPengguna(); 
           data[4] = pengguna.getNoPengguna(); 
           dtm.addRow(data); 
       }
    }
    
     public final void getOneData() {
        String searchNama = txtSearching.getText().trim();

        if (searchNama.isEmpty()) {
            getData();
            return;
        }

        DataPengguna dataPengguna = conData.findNama(searchNama);

        if (dataPengguna != null) {
   
            DefaultTableModel dtm = (DefaultTableModel) dataAnggota.getModel();
            dtm.setRowCount(0); 
            
            Object[] data = new Object[5];
            
            data[0] = dataPengguna.getIdPengguna();
            data[1] = dataPengguna.getNamaPengguna();
            data[2] = dataPengguna.getEmailPengguna();
            data[3] = dataPengguna.getAlamatPengguna();
            data[4] = dataPengguna.getNoPengguna();
            dtm.addRow(data);
        } else {
            JOptionPane.showMessageDialog(txtSearching, "Data dengan nama " + searchNama + " tidak ditemukan.",
                "Peringatan", JOptionPane.WARNING_MESSAGE);

            DefaultTableModel dtm = (DefaultTableModel) dataAnggota.getModel();
            dtm.setRowCount(0); // Bersihkan tabel jika tidak ada data ditemukan
                }
    }
    

    
    private void clearData() {
        txtNoHp.setText("");
        txtEmail.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtSearching.setText("");
        txtNoHp.setEditable(true);
        txtEmail.setEditable(true);
        txtNama.setEditable(true);
        txtAlamat.setEditable(true);
        txtSearching.setEditable(true);
    }
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelNavbar13 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JLabel();
        btnViewTransaksi = new rojerusan.RSMaterialButtonRectangle();
        btnViewPengguna = new rojerusan.RSMaterialButtonRectangle();
        jPanel2 = new javax.swing.JPanel();
        labelharga = new javax.swing.JLabel();
        labeltglmasuk = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataAnggota = new javax.swing.JTable();
        txtSearching = new javax.swing.JTextField();
        btnSubmited = new rojerusan.RSMaterialButtonRectangle();
        btnUpdated = new rojerusan.RSMaterialButtonRectangle();
        btnDeleted = new rojerusan.RSMaterialButtonRectangle();
        btnCleared = new rojerusan.RSMaterialButtonRectangle();
        txtNama = new javax.swing.JTextField();
        txtNoHp = new javax.swing.JTextField();
        labelnama = new javax.swing.JLabel();
        labeltglmasuk1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1198, 668));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Keanggotaan");

        panelNavbar13.setBackground(new java.awt.Color(204, 204, 204));

        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\PBO\\PROJECT_UAS\\Img\\Fitness-Gym-logo-design-template-on-transparent-background-PNG__1_-removebg-preview (2).png")); // NOI18N

        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\PBO\\PROJECT_UAS\\Img\\logout (1).png")); // NOI18N
        btnlogout.setText("LogOut");
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
        });

        btnViewTransaksi.setBackground(new java.awt.Color(153, 153, 153));
        btnViewTransaksi.setText("Transaksi");
        btnViewTransaksi.setToolTipText("");
        btnViewTransaksi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnViewTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTransaksiActionPerformed(evt);
            }
        });

        btnViewPengguna.setBackground(new java.awt.Color(153, 153, 153));
        btnViewPengguna.setText("Data Anggota");
        btnViewPengguna.setToolTipText("");
        btnViewPengguna.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnViewPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPenggunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNavbar13Layout = new javax.swing.GroupLayout(panelNavbar13);
        panelNavbar13.setLayout(panelNavbar13Layout);
        panelNavbar13Layout.setHorizontalGroup(
            panelNavbar13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavbar13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnlogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNavbar13Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(panelNavbar13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(30, 30, 30))
        );
        panelNavbar13Layout.setVerticalGroup(
            panelNavbar13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavbar13Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel40)
                .addGap(152, 152, 152)
                .addComponent(btnViewTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        labelharga.setText("No Pengguna");

        labeltglmasuk.setText("Alamat");

        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtAlamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });

        dataAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAMA", "Email", "Alamat", "No Pengguna"
            }
        ));
        dataAnggota.setGridColor(new java.awt.Color(153, 153, 153));
        dataAnggota.setShowGrid(true);
        dataAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataAnggota);
        if (dataAnggota.getColumnModel().getColumnCount() > 0) {
            dataAnggota.getColumnModel().getColumn(0).setResizable(false);
        }

        txtSearching.setForeground(new java.awt.Color(204, 204, 204));
        txtSearching.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchingKeyReleased(evt);
            }
        });

        btnSubmited.setText("CREATE");
        btnSubmited.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        btnSubmited.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitedActionPerformed(evt);
            }
        });

        btnUpdated.setBackground(new java.awt.Color(255, 204, 0));
        btnUpdated.setText("UPDATE");
        btnUpdated.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        btnUpdated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatedActionPerformed(evt);
            }
        });

        btnDeleted.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleted.setText("DELETE");
        btnDeleted.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        btnDeleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletedActionPerformed(evt);
            }
        });

        btnCleared.setBackground(new java.awt.Color(102, 255, 102));
        btnCleared.setText("Clear");
        btnCleared.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        btnCleared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearedActionPerformed(evt);
            }
        });

        txtNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtNoHp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoHpActionPerformed(evt);
            }
        });

        labelnama.setText("Nama");

        labeltglmasuk1.setText("Email");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnDeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelnama)
                                .addGap(18, 18, 18)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labeltglmasuk1)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(158, 158, 158)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSubmited, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labeltglmasuk)
                            .addComponent(labelharga))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearching, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltglmasuk))
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeltglmasuk1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelharga)
                    .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmited, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(txtSearching, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelNavbar13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel1)
                        .addContainerGap(364, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelNavbar13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(ViewDataAnggota.this,
            "Are you sure you want to logout?", "Logout Confirmation",
            JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            user.setRole(null); // Clear user role
            user.setUsername(null); // Clear username
            JOptionPane.showMessageDialog(ViewDataAnggota.this, "You have been logged out.");
            dispose(); // Close AdminDashboard
            new ViewLogIn().setVisible(true); // Open Login Form
        }
    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnViewTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTransaksiActionPerformed
        // TODO add your handling code here:
        new ViewTransaksi(user).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewTransaksiActionPerformed

    private void btnViewPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewPenggunaActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtSearchingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchingKeyReleased
        // TODO add your handling code here:
        getOneData();
    }//GEN-LAST:event_txtSearchingKeyReleased

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHpActionPerformed

    private void btnClearedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearedActionPerformed
        // TODO add your handling code here:
        getData();
        clearData();
    }//GEN-LAST:event_btnClearedActionPerformed

    private void btnUpdatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatedActionPerformed
        // TODO add your handling code here:
        int i = dataAnggota.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(btnUpdated, "Harap pilih salah satu data",
                "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Ambil ID Pengguna dari tabel
            String idPengguna = dataAnggota.getModel().getValueAt(i, 0).toString();

            String namaPengguna = txtNama.getText().trim();
            String emailPengguna = txtEmail.getText().trim();
            String alamatPengguna = txtAlamat.getText().trim();
            String nomorPengguna = txtNoHp.getText().trim();

            if (namaPengguna.isEmpty() || emailPengguna.isEmpty() || alamatPengguna.isEmpty() || nomorPengguna.isEmpty()) {
                JOptionPane.showMessageDialog(btnUpdated, "Semua input harus diisi.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Siapkan model DataPengguna
            DataPengguna pengguna = new DataPengguna();
            pengguna.setNamaPengguna(namaPengguna);
            pengguna.setEmailPengguna(emailPengguna);
            pengguna.setAlamatPengguna(alamatPengguna);
            pengguna.setNoPengguna(nomorPengguna);

            // Update data pengguna menggunakan PenggunaCRUD
            PenggunaCRUD penggunaCRUD = new PenggunaCRUD(new ConnectionManager());
            penggunaCRUD.update(idPengguna, pengguna);

            // Notifikasi sukses
            JOptionPane.showMessageDialog(btnUpdated, "Data berhasil diperbarui.");
            getData(); // Refresh tabel
            clearData(); // Kosongkan inputan
        } catch (Exception e) {
            JOptionPane.showMessageDialog(btnUpdated, "Terjadi kesalahan: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdatedActionPerformed

    private void btnSubmitedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitedActionPerformed
        // TODO add your handling code here:
        try {
            // Konfirmasi pembayaran
            int response = JOptionPane.showConfirmDialog(this, "Apakah Data sudah Valid?",
                "", JOptionPane.YES_NO_OPTION);

            if (response == JOptionPane.YES_OPTION) {
               
                DataPengguna pengguna = new DataPengguna();
                pengguna.setNamaPengguna(txtNama.getText().trim());
                pengguna.setEmailPengguna(txtEmail.getText().trim());
                pengguna.setAlamatPengguna(txtAlamat.getText().trim());
                pengguna.setNoPengguna(txtNoHp.getText().trim());

                // Validasi input
                if (pengguna.getNamaPengguna().isEmpty() || pengguna.getNoPengguna().isEmpty() ||
                    pengguna.getEmailPengguna().isEmpty() || pengguna.getAlamatPengguna().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                conData.create(pengguna);

                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Pesan", JOptionPane.INFORMATION_MESSAGE);

                getData();
                clearData();
            } else {
                JOptionPane.showMessageDialog(this, "Proses dibatalkan", "Batal", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSubmitedActionPerformed

    private void btnDeletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletedActionPerformed
        // TODO add your handling code here:
        int i = dataAnggota.getSelectedRow();

        if (i == -1) {
            JOptionPane.showMessageDialog(btnDeleted, "Harap pilih salah satu data",
                "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int id = Integer.parseInt(dataAnggota.getModel().
            getValueAt(i, 0).toString());

        conData.delete(id);
        JOptionPane.showMessageDialog(btnDeleted, "Data berhasil diHapus");
        getData();
        clearData();
    }//GEN-LAST:event_btnDeletedActionPerformed

    private void dataAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataAnggotaMouseClicked
        // TODO add your handling code here:
        int i = dataAnggota.getSelectedRow();

        TableModel model = dataAnggota.getModel();
        txtNama.setText(model.getValueAt(i, 1).toString());
        txtEmail.setText(model.getValueAt(i, 2).toString());
        txtAlamat.setText(model.getValueAt(i, 3).toString());
        txtNoHp.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_dataAnggotaMouseClicked
    
    private void printStruk(String struk) {
    PrinterJob printerJob = PrinterJob.getPrinterJob();
    printerJob.setPrintable(new Printable() {
        @Override
        public int print(Graphics g, PageFormat pf, int page) throws PrinterException {
            if (page > 0) {
                return NO_SUCH_PAGE;
            }

            Graphics2D g2d = (Graphics2D) g;
            g2d.setFont(new Font("Courier", Font.PLAIN, 12)); // Menggunakan font monospasi
            g2d.translate(pf.getImageableX(), pf.getImageableY());

            // Memisahkan struk menjadi baris-baris
            String[] lines = struk.split("\n");
            int y = 20; // Posisi awal y
            for (String line : lines) {
                g2d.drawString(line, 10, y); // Posisi x = 10, y meningkat setiap baris
                y += 15; // Menambah jarak antar baris
            }

            return PAGE_EXISTS;
        }
    });

    boolean doPrint = printerJob.printDialog();
    if (doPrint) {
        try {
            printerJob.print();
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak struk: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnCleared;
    private rojerusan.RSMaterialButtonRectangle btnDeleted;
    private rojerusan.RSMaterialButtonRectangle btnSubmited;
    private rojerusan.RSMaterialButtonRectangle btnUpdated;
    private rojerusan.RSMaterialButtonRectangle btnViewPengguna;
    private rojerusan.RSMaterialButtonRectangle btnViewTransaksi;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JTable dataAnggota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelharga;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labeltglmasuk;
    private javax.swing.JLabel labeltglmasuk1;
    private javax.swing.JPanel panelNavbar13;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JTextField txtSearching;
    // End of variables declaration//GEN-END:variables
}
